export {default as logo} from "./logo.png"
export {default as logo2} from "./logo2.png"
export { default as mainbook } from "./Home/mainbook.png"
export {default as bk2} from "./Home/bk2.jpg"
export {default as bk3} from "./Home/bk3.jpg"
export {default as bk4} from "./Home/bk4.jpg"
export {default as bk5} from "./Home/bk5.jpg"
export {default as bk6} from "./Home/bk6.jpg"
export {default as bk1} from "./Home/bk1.jpg"
export {default as bk7} from "./Home/bk7.jpg"
export {default as bk8} from "./Home/bk8.jpg"
export {default as lcp} from "./Home/lcp.png"
export {default as error} from "./Error/error.jpg"
export {default as header} from "./catalogue/header.jpg"
export {default as empty_cart} from "./cart/empty_cart.jpg"
export {default as google} from "./google.svg"
export {default as Loader} from "./Loader/Loader.svg"
export {default as headshot} from "./Bookdetails/headshot.jpg"
export {default as headshot2} from "./Bookdetails/headshot2.jpg"
export {default as headshot3} from "./Bookdetails/headshot3.jpg"
export {default as headshot4} from "./Bookdetails/headshot4.jpg"
export {default as headshot5} from "./Bookdetails/headshot5.jpg"
2